// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssqzjyspwifyolzswghw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcXpqeXNwd2lmeW9senN3Z2h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTA1MDEsImV4cCI6MjA2Mzg4NjUwMX0.0ELZ0tHwIz2ET3gTwxagpa3JpHgV2Qyo3rZzfnl7MqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);